package com.sec.internal.constants.ims.servicemodules.im.reason;

public enum ImSessionClosedReason {
    NONE,
    CLOSED_BY_REMOTE,
    CLOSED_BY_LOCAL,
    CLOSED_INVOLUNTARILY,
    KICKED_OUT_BY_LEADER,
    GROUP_CHAT_DISMISSED,
    MAX_GROUP_NUMBER_REACHED,
    CLOSED_WITH_480_REASON_CODE,
    CLOSED_WITH_408_REASON_CODE,
    LEFT_BY_SERVER,
    ALL_PARTICIPANTS_LEFT,
    LEAVE_SESSION_FAILED,
    LEAVE_SESSION_PENDING
}
