package com.sec.internal.constants.ims.cmstore.omanetapi;

import com.sec.internal.constants.ims.entitilement.SoftphoneNamespaces;
import com.sec.internal.ims.cmstore.omanetapi.FaxHandler;
import com.sec.internal.ims.core.RegistrationEvents;
import com.sec.internal.ims.core.handler.secims.imsCommonStruc.Id;
import org.xbill.DNS.Type;

public enum OMASyncEventType {
    DEFAULT(0),
    CREDENTIAL_EXPIRED(256),
    MSTORE_REDIRECT(Type.CAA),
    SELF_RETRY(258),
    API_SUCCEED(259),
    MOVE_ON(260),
    START_INITIAL_SYNC(513),
    INITIAL_SYNC_CONTINUE_SEARCH(514),
    PAUSE_INITIAL_SYNC(515),
    CANCEL_INITIAL_SYNC(516),
    INITIAL_SYNC_COMPLETE(517),
    INITIAL_SYNC_SUMMARY_COMPLETE(518),
    OBJECT_START_DOWNLOAD(519),
    OBJECT_ONE_DOWNLOAD_COMPLETED(Id.REQUEST_SLM_SEND_MSG),
    OBJECT_END_DOWNLOAD(Id.REQUEST_SLM_SEND_FILE),
    OBJECT_START_UPLOAD(Id.REQUEST_SLM_CANCEL_SESSION),
    OBJECT_ONE_UPLOAD_COMPLETED(Id.REQUEST_ACCEPT_SLM_LMM_SESSION),
    OBJECT_END_UPLOAD(Id.REQUEST_REJECT_SLM_LMM_SESSION),
    OBJECT_BULK_UPLOAD_COMPLETED(Id.REQUEST_IM_SET_MORE_INFO_TO_SIP_UA),
    FALLBACK_ONE_UPLOAD(526),
    SYNC_ERR(527),
    ONE_LINE_INIT_SYNC_COMPLETE(528),
    ALL_LINE_INIT_SYNC_COMPLETE(529),
    CANCEL_LINE_INITIAL_SYNC(530),
    INITSYNC_LINE_ADDED(531),
    INITSYNC_LINE_REMOVED(532),
    INITSYNC_LINE_EXPIRED(533),
    INITSYNC_LINE_REFRESHED(534),
    FALLBACK_ONE_UPDATE_OR_DELETE(535),
    REQUEST_OPSEARCH_AFTER_PSF_REMOVED(536),
    CREATE_NOTIFICATION_CHANNEL(769),
    CHECK_NOTIFICATION_CHANNEL(770),
    CHECK_SUBSCRIPTION_AND_START_LONG_POLLING(771),
    CREATE_SUBSCRIPTION_CHANNEL(772),
    DELETE_SUBCRIPTION_CHANNEL(773),
    UPDATE_SUBSCRIPTION_CHANNEL(774),
    MAILBOX_RESET(775),
    CLOUD_UPDATE(776),
    DOWNLOAD_RETRIVED(FaxHandler.RETRIEVE_FAX),
    OBJECT_AND_PAYLOAD_DOWNLOAD(778),
    OBJECTS_AND_PAYLOAD_DOWNLOAD_COMPLETE(779),
    SEND_LONG_POLLING_REQUEST(780),
    NORMAL_SYNC_COMPLETE(781),
    START(782),
    RESUME(783),
    STOP(784),
    NORMAL_SYNC_LINE_ADDED(785),
    NORMAL_SYNC_LINE_REMOVED(786),
    NORMAL_SYNC_LINE_EXPIRED(787),
    NORMAL_SYNC_LINE_REFRESHED(788),
    ONE_LINE_NORMAL_SYNC_COMPLETE(789),
    ALL_LINE_NORMAL_SYNC_COMPLETE(790),
    CANCEL_DOWNLOADING(791),
    RESUME_DOWNLOADING(792),
    DELETE_NOTIFICATION_CHANNEL(793),
    PAUSE(800),
    ONE_POLLING_FINISHED(801),
    CREATE_SUBSCRIPTION_FINISHED(802),
    GET_GCM_TOKEN_FROM_VSIM(803),
    UPDATE_NOTIFICATIONCHANNEL_LIFETIME(804),
    CHECK_ACTIVE_NOTIFICATIONCHANNEL(805),
    RESET_STATE(806),
    CREATE_NOTIFICATION_CHANNEL_FINISHED(807),
    DELETE_NOTIFICATION_SUBSCRIPTION_RESOURCE(Id.REQUEST_XDM_DELETE_CONTACT),
    REQUEST_SUBSCRIPTION_AFTER_PSF_REMOVED(RegistrationEvents.EVENT_CONTACT_ACTIVATED),
    UPDATE_SUBSCRIPTION_CHANNEL_DELAY(816),
    REMOVE_UPDATE_SUBSCRIPTION_CHANNEL(817),
    PUT_OBJECT(1025),
    UPDATE_ONE_SUCCESSFUL(SoftphoneNamespaces.SoftphoneEvents.EVENT_USER_SWITCH_BACK),
    UPDATE_FAILED(SoftphoneNamespaces.SoftphoneEvents.EVENT_RETRY_OBTAIN_ACCESS_TOKEN),
    UPDATE_COMPLETED(SoftphoneNamespaces.SoftphoneEvents.EVENT_RELOGIN),
    TRANSIT_TO_START(1029),
    TRANSIT_TO_RESUME(SoftphoneNamespaces.SoftphoneEvents.EVENT_START_RELOGIN),
    TRANSIT_TO_PAUSE(SoftphoneNamespaces.SoftphoneEvents.EVENT_AIRPLANE_MODE_ON),
    TRANSIT_TO_STOP(SoftphoneNamespaces.SoftphoneEvents.EVENT_NETWORK_CONNECTED),
    UPDATE_NEXT(SoftphoneNamespaces.SoftphoneEvents.EVENT_OUT_OF_SERVICE),
    BULK_UPDATE_OR_DELETE_SUCCESSFUL(SoftphoneNamespaces.SoftphoneEvents.EVENT_REQUEST_AKA_CHALLENGE_DONE),
    FLAG_SYNC_LINE_ADDED(1184),
    FLAG_SYNC_LINE_REMOVED(1185),
    FLAG_SYNC_LINE_EXPIRED(1186),
    FLAG_SYNC_LINE_REFRESHED(1187),
    ONE_LINE_FLAG_SYNC_COMPLETE(1188),
    ALL_LINE_FLAG_SYNC_COMPLETE(1189),
    ADD_TO_WORKINGQUEUE(1190),
    ADD_TO_UPLOADWORKINGQUEUE(1191),
    ADD_TO_QUEUE_BULKDELETE(1192),
    ADD_TO_QUEUE_BULKUPDATE(1193),
    ADD_TO_QUEUE_BULKUPLOAD(1194),
    EVENT_VVM_DATA_UPDATE(1281),
    SEARCH_GREETING(1282),
    DELETE_GREETING(1283),
    UPLOAD_GREETING(1284),
    VVM_CHANGE_ERROR(1285),
    VVM_CHANGE_SUCCEED(1286),
    VVM_NOTIFY(1287),
    SEND_LARGE_DATA_POLLING_REQUEST(1537),
    SEND_LARGE_DATA_POLLING_FINISHED(1538),
    EVENT_TYPE_END(Integer.MAX_VALUE);
    
    private final int mId;

    private OMASyncEventType(int id) {
        this.mId = id;
    }

    public int getId() {
        return this.mId;
    }

    public static OMASyncEventType valueOf(int id) {
        for (OMASyncEventType r : values()) {
            if (r.mId == id) {
                return r;
            }
        }
        return null;
    }
}
