package com.sec.internal.ims.servicemodules.csh.event;

public enum CshErrorReason {
    SUCCESS,
    USER_BUSY,
    TEMPORAIRLY_NOT_AVAILABLE,
    REQUEST_TIMED_OUT,
    USER_NOT_FOUND,
    CANCELED,
    REJECTED,
    ENGINE_ERROR,
    FILE_IO,
    REMOTE_CONNECTION_CLOSED,
    FORMAT_NOT_SUPPORTED,
    ACK_TIMEOUT,
    FORBIDDEN,
    NOT_REACHABLE,
    BEARER_LOST,
    ACK_TIMED_OUT,
    RTP_RTCP_TIMEOUT,
    MSRP_TIMEOUT,
    CSH_CAM_ERROR,
    NORMAL,
    UNKNOWN,
    NONE
}
